spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studywords?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource


  mvc:
    #配置它以后移动html页面就不用改路径了！
    static-path-pattern: /static/**    #静态资源的请求方式
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录

  mail:
    host: smtp.qq.com
    username: 1574172532@qq.com  # 邮箱地址
    password: fqdkjczncgzebadf # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  thymeleaf:
    mode: HTML
    cache: false
    check-template-location: on
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chun.myspringboot.pojo
  configuration:
    map-underscore-to-camel-case: on #采用驼峰标识
#评论头像
comment.avatar: /images/avatar.png

# pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


